services:


  backend:
    build:
      context: ../  # Change context to parent directory to include shared-packages
      dockerfile: project-a/Dockerfile
    ports:
      - "${API_PORT-5001}:${API_PORT-5001}"  # Changed to 5001
    working_dir: /app/project-a/
    volumes:
      - .:/app/project-a/
      - ../shared-packages:/app/shared-packages  # Mount shared packages
    command: sh -c "python app/main.py"
    environment:
      PYTHONPATH: "/app:/app/project-a:/app/shared-packages/common-utils/src:/app/shared-packages/data-models/src"

networks:
  external-network:
    external: true
